services:
  basic-server:
    image: kotlin-ktor-starter
    container_name: kotlin-ktor-server
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      APP: /opt/applications/basic-server.jar
  data-analyzer:
    image: kotlin-ktor-starter
    container_name: kotlin-ktor-analyzer
    ports:
      - "8887:8887"
    environment:
      PORT: 8887
      APP: /opt/applications/data-analyzer-server.jar
  data-collector:
    image: kotlin-ktor-starter
    container_name: kotlin-ktor-collector
    ports:
      - "8886:8886"
    environment:
      PORT: 8886
      APP: /opt/applications/data-collector-server.jar
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: email-verifier-rabbit
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq

configs:
  plugins:
    content: "[rabbitmq_consistent_hash_exchange]."